### ISSUE TITLE
error on pip install

### ISSUE THREAD

**Issue by timkpaine** [timkpaine/jupyterlab_celltests#37]
@vidartf does this look familiar at all

```bash
λ pip3 install .
Processing /Users/theocean154/Programs/projects/jupyter/jupyterlab_celltests
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/9t/gh_cb61x61v5v16hqhp31n440000gn/T/pip-build-env-p5qs4ixy/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel jupyter-packaging
       cwd: None
  Complete output (24 lines):
  Traceback (most recent call last):
    File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
      from pip._internal.cli.autocompletion import autocomplete
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
      from pip._internal.cli.main_parser import create_main_parser
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
      from pip._internal.cli import cmdoptions
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
      from pip._internal.models.search_scope import SearchScope
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/models/search_scope.py", line 11, in <module>
      from pip._internal.utils.misc import normalize_path, redact_password_from_url
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 58, in <module>
      from typing import cast, Tuple
    File "/usr/local/lib/python3.7/site-packages/typing.py", line 1356, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/usr/local/lib/python3.7/site-packages/typing.py", line 1004, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/9t/gh_cb61x61v5v16hqhp31n440000gn/T/pip-build-env-p5qs4ixy/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel jupyter-packaging Check the logs for full command output.
```

**Comment by timkpaine** [comment]
bad `typing` module, removed and working now
